<?php

namespace ShortUrlBundle\Repository;

/**
 * Urls_tableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Urls_tableRepository extends \Doctrine\ORM\EntityRepository
{
}
